In [1]:
import torch
import numpy as np

# The way of using the test function:
In Bayesian Optimization for Botorch, it is required to transformed input data X in the range between 0 and 1. However, the domain of interest for the test cases are often not in this range. Therefore, the process requires scaling the X back to the domain of interest after performing BO to get the correct objective value.


In our test function scripts, it contains the scaling function for each problem and the objective calculation function. The process of using it is shown as follow:
1. Initialize x in [0,1]
2. Use the scaling function to scale the x to the domain of interest
3. Pass into the test case function to get the constraints values and the objective

In [2]:
# Select your test case
from test_functions.Ackley2D import Ackley2D, Ackley2D_Scaling

# Initialized sample in the correct dimension based on the test case
# The test case need to have X in [0,1]
X = torch.rand(20,2)
print(X)


tensor([[0.0227, 0.4598],
        [0.6527, 0.8014],
        [0.8639, 0.8178],
        [0.7373, 0.7472],
        [0.7691, 0.2556],
        [0.4449, 0.8300],
        [0.0509, 0.3364],
        [0.6180, 0.9053],
        [0.0164, 0.1349],
        [0.9096, 0.3481],
        [0.5736, 0.5184],
        [0.0836, 0.3022],
        [0.6346, 0.3717],
        [0.5135, 0.9840],
        [0.8060, 0.3734],
        [0.2095, 0.1903],
        [0.8411, 0.6314],
        [0.7652, 0.6092],
        [0.2833, 0.5461],
        [0.0456, 0.6024]])


In [3]:
# Scale the X in [0,1] to the domain of interest
X_scaled = Ackley2D_Scaling(X)

# The test case output the gx (constaint) and fx (objective)
gx, fx = Ackley2D(X_scaled)
print(fx)
print(gx)

tensor([[-11.7617],
        [-14.8471],
        [-16.8226],
        [-15.0416],
        [-14.1062],
        [-15.4325],
        [-10.0456],
        [-16.9552],
        [-12.0080],
        [-16.0302],
        [-11.4791],
        [-10.3865],
        [-11.8268],
        [-17.0520],
        [-14.3887],
        [ -7.4730],
        [-16.5612],
        [-15.1302],
        [ -8.9436],
        [-12.7158]])
tensor([[-2.7627,  0.0308],
        [11.8104,  3.4988],
        [15.2247,  5.7766],
        [12.2678,  3.6753],
        [ 5.3717,  1.6401],
        [ 9.1240,  2.6361],
        [-4.1910, -0.7635],
        [12.8493,  4.5832],
        [-7.7311,  0.6094],
        [ 8.8656,  3.6463],
        [ 6.3792, -0.4514],
        [-4.2132, -1.2251],
        [ 5.0938, -0.4448],
        [12.4624,  5.1271],
        [ 7.6916,  2.1160],
        [-4.0026, -2.1624],
        [12.0883,  3.8323],
        [10.6153,  2.6864],
        [ 2.4418, -1.7210],
        [-0.2793,  0.9093]])
